
spring:
    servlet:
        multipart:
            max-file-size: 300MB
            max-request-size: 300MB

family:
    family-name: happy family
    father:
        name: tom
        age: 35
    mother:
        alias:
            - lovely
            - alice
    child:
        name: jack
        age: 5
        friends:
            - hobby: football
              gender: male
            - hobby: sing
              gender: female




